### ISSUE TITLE
MVP Get Involved Page

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/website#3]
Currently, the get involved section is where small on the main page.
We want to turn that into something bigger and also honour all our fabulous contributors.

## Tasks
- [x] Create Contributors Showcase Component (#38) 
- [x] Brainstorm ways for people to get involved
- [ ] Stretch goal: Automatically merge all repositories contributors via cron like Github Action
- [ ] Have a [list of good first issues](https://github.com/search?utf8=✓&q=user%3Aopenclimatefix+label%3A"good+first+issue"&type=Issues&ref=advsearch&l=&l=) on there

## Mockup
![image](https://user-images.githubusercontent.com/6052785/68707934-957f6000-058a-11ea-897b-24ff3b943888.png)

**Comment by ollicle** [comment]
A list of contributors could help fill out and provide some community feeling to a **Get involved** page. This would be encouraging to potential new contributors.

Although it seems this page would still be a bit sparse with only the current content. Is there more that could be written on getting involved?

**Comment by flowirtz** [comment]
Great suggestion, thanks. Yes, I agree, the "getting involved" bit as a whole is very sparse atm.
Originally it was it's own page, but it was pretty much just a rewrite of [Jack's blog post](https://openclimatefix.org/blog/2019-03-06-how-to-get-involved). I am all for bringing it back though. Having the contributors also on there seems like a great idea.
Would also mean we could have one central Call to Action that catches every group of people.

I'd like to brainstorm this more, as I'm not sure about all the things we could put on there.
@JackKelly or @dctanner, maybe you also have ideas about this?

**Comment by JackKelly** [comment]
I definitely agree that it'd be great to have a list of contributors :)

I don't have strong feelings about whether we split contributors into different classes (e.g. 'website contributor' or 'ML researcher', etc.).  My hunch is that, at least for now, maybe we shouldn't split contributors into different classes (i.e. we just have a single list of names, maybe in alphabetical order).   But I'm happy to be persuaded otherwise!

For now, we don't have many contributors to the ML projects :)  So, at least for now, I'm happy to manually maintain a list of contributors to other projects.  If this becomes unmaintainable then I wonder if there's a way to use github's API to request all contributors?

**Comment by flowirtz** [comment]
@JackKelly agreed, I think for now we shouldn't split it.
I'll rework this issue a bit and turn it into an epic, to revamp the "Get Involved" bit into an independent page, including all collaborators.

GitHub does expose an API and via GitHub Actions we should be able to run a cron like job every x days/minutes to do the job. I wanted to play around with Actions anyway. Will raise an issue and then tackle it if nobody beats me to it. 😊🏎
First definitely manual list though, yes. Ideally extended from the [`.all-contributorsrc`](https://github.com/openclimatefix/website/blob/master/.all-contributorsrc) we already have in this repo.

**Comment by flowirtz** [comment]
@ollicle @JackKelly I updated the description of this issue and added an initial mockup of what the contributors section could look like. What do you guys think?

**Comment by ollicle** [comment]
This page would be a good place to list (if GitHub API enables?) or at least link to the [good first issue](https://github.com/openclimatefix/website/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) list.

**Comment by flowirtz** [comment]
Love the idea! Was just able to create this [query to list them across all our repos](https://github.com/search?utf8=✓&q=user%3Aopenclimatefix+label%3A"good+first+issue"&type=Issues&ref=advsearch&l=&l=), I guess it's possible to get that data via the api as well then.
Any other ideas for this page, @ollicle? 😊

**Comment by ollicle** [comment]
Best to let the content of the page be the driver here, and the means to expand that paragraph of Lorem Ipsum in your concept is captured well with **Brainstorm ways for people to get involved**. 

So what does the project need?

While I’m here – I noticed you can filter out closed issues: [open good first issues](https://github.com/search?utf8=%E2%9C%93&q=user%3Aopenclimatefix+label%3A%22good+first+issue%22+state%3Aopen&type=Issues&ref=advsearch&l=&l=)

**Comment by JackKelly** [comment]
> I updated the description of this issue and added an initial mockup of what the contributors section could look like. What do you guys think?

Looks good to me!  Thanks!

**Comment by drwm-base** [comment]
I would like to create an early version of this page, with the contributors component I created in #39 .  I would include navigation to the page, a link to the good first issues, the contributors showcase component, and anything you would like to say on the page itself. I might even look into Github API, however I'd imagine it involves getting a key for this repository which I don't believe I can do. 

Anyways I'd like to look into it.

**Comment by flowirtz** [comment]
Sounds awesome @drwm-base! I'll give you a review on #39 this evening and hope to get it merged.
Maybe leave some space for a `<p>` or two and then I can scrape together some blurp to put in there.
For a first version that's more than great.

**Comment by drwm-base** [comment]
Thanks @FWirtz I am currently looking into the Github API, which seems simpler than I originally thought. I think I could get a list of "good first issues" published on a component on the page as well. Still looking into it.

Just to be clear, do you want a list of all "good first issues" across openclimatefix repositories?

**Comment by flowirtz** [comment]
@drwm-base that would be amazing! Yes, across all ocf repos, if possible. 😊

**Comment by drwm-base** [comment]
@FWirtz so in order to pull github data, I need to use the github graphql api. In order to do that, I need a github token to get access to the graphql api, which you shouldn't share publicly according to github. In order to fetch github api data, you need to set up a github app, which is a whole process (it needs to be hosted, given scopes, etc). This is certainly an issue that needs to be addressed internally if it's something you want to do. So my PR will include a link to the good first issues created by ocf, as previously discussed. I will have a PR up tomorrow for you to look at.

**Comment by drwm-base** [comment]
If this is too much or too complicated, I can just leave it at a link.

**Comment by drwm-base** [comment]
I also found a gatsby plugin to add basic github api access without a token, if that's something you're interested in. I'm going to get a pull request up with just the basic link and then we can talk in the PR. 

The plugin is here: https://www.gatsbyjs.org/packages/gatsby-source-apiserver/?=apiser

**Comment by flowirtz** [comment]
@drwm-base Aaaah fair enough, sounds more than good for now.
Thank you David!
